# Generated by Django 4.2.6 on 2024-05-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='course_joined',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
