# Generated by Django 4.2.6 on 2024-05-11 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='course/blog')),
                ('video_embed_link', models.CharField(blank=True, null=True, verbose_name='embed video')),
                ('title', models.CharField(verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('visible', models.BooleanField(default=True, verbose_name='Görünür mü?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('like_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='Yorum')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Kategori Adı')),
                ('icon', models.ImageField(upload_to='course/kategori_logo', verbose_name='Kategori İkon')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('index', models.IntegerField(default=1, verbose_name='Sıra no')),
                ('ai_category', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='CompletedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(verbose_name='Kupon Kodu')),
                ('limit', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Kupon Limiti (Adet*)')),
                ('discount_percent', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='İndirim (%*)')),
                ('discount_amount', models.FloatField(blank=True, null=True, verbose_name='İndirim (Tutar TL*)')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Kurs Başlığı')),
                ('desc', models.CharField(verbose_name='Kurs Açıklaması')),
                ('banner', models.ImageField(upload_to='course/courses')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_list', models.JSONField(blank=True, default=dict, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Bölüm Adı')),
                ('index', models.IntegerField(default=1, verbose_name='Sıra no')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='CourseSectionLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Kurs Başlığı')),
                ('content', models.TextField(blank=True, null=True, verbose_name='İçerik')),
                ('vimeo_embed_link', models.CharField(blank=True, null=True, verbose_name='Vimeo Embed Link')),
                ('video_time', models.CharField(blank=True, null=True)),
                ('index', models.IntegerField(default=1, verbose_name='Sıra no')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Soru')),
                ('reply', models.TextField(verbose_name='Cevap')),
                ('index', models.IntegerField(default=1, verbose_name='Sıra no')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Soru Başlığı')),
                ('details', models.CharField(verbose_name='Detaylar')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HelpComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='Yorum')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Bildirim Başlığı')),
                ('desc', models.CharField(verbose_name='Kısa Açıklama')),
                ('button_link', models.CharField(blank=True, null=True, verbose_name='Buton Linki')),
                ('banner', models.ImageField(upload_to='course/slider')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Bildirim Başlığı')),
                ('sender', models.CharField(default='Yapay Arşiv')),
                ('link', models.CharField(blank=True, null=True)),
                ('system', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing', models.BooleanField(default=False)),
                ('sound_status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-notification__date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Site AnaSayfa Başlığı')),
                ('desc', models.CharField(verbose_name='Site Meta Açıklama')),
                ('keywords', models.CharField(verbose_name='Site Meta Anahtar Kelimeler')),
                ('fav_icon', models.FileField(blank=True, null=True, upload_to='course/site_images', verbose_name='Fav İcon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='course/site_images', verbose_name='Site Logo')),
                ('dark_logo', models.ImageField(blank=True, null=True, upload_to='course/site_images', verbose_name='Site Dark Logo')),
            ],
        ),
        migrations.CreateModel(
            name='UserBlogLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserHelpLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_oid', models.CharField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0, verbose_name='Tutar')),
                ('status', models.BooleanField(blank=True, default=None, null=True)),
                ('checked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
