# Generated by Django 4.2.6 on 2024-05-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayments',
            name='coupon_code',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
