# Generated by Django 4.2.6 on 2024-05-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_blogcomments_like_count_helpcomments_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Başlık'),
        ),
    ]
